"""seed table changes

Revision ID: 1bde8f971ed7
Revises: 7b4c22f01cec
Create Date: 2022-12-03 13:00:36.271015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bde8f971ed7'
down_revision = '7b4c22f01cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Password')
    # ### end Alembic commands ###
