"""seed tables

Revision ID: 4358abf39d78
Revises: 
Create Date: 2022-12-03 12:46:20.145587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4358abf39d78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('Firstname', sa.String(), nullable=True),
    sa.Column('Lastname', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.Column('OptIntoPhyStatements', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('Username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
