"""seed table changes

Revision ID: 7b4c22f01cec
Revises: 4358abf39d78
Create Date: 2022-12-03 12:49:56.448407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4c22f01cec'
down_revision = '4358abf39d78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backaccounts',
    sa.Column('AccountID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.String(), nullable=False),
    sa.Column('AccountType', sa.String(), nullable=True),
    sa.Column('AccountBalance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('AccountID', 'UserID'),
    sa.UniqueConstraint('AccountID'),
    sa.UniqueConstraint('UserID')
    )
    op.create_table('scheduledtransactions',
    sa.Column('TransactionID', sa.Integer(), nullable=False),
    sa.Column('AccountID', sa.String(), nullable=False),
    sa.Column('ReceivingAccountID', sa.String(), nullable=True),
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('TransactionAmount', sa.String(), nullable=True),
    sa.Column('Comment', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('TransactionID', 'AccountID'),
    sa.UniqueConstraint('AccountID'),
    sa.UniqueConstraint('TransactionID')
    )
    op.add_column('users', sa.Column('UserID', sa.Integer(), nullable=False))
    op.drop_column('users', 'UserId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('UserId', sa.INTEGER(), server_default=sa.text('nextval(\'"users_UserId_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('users', 'UserID')
    op.drop_table('scheduledtransactions')
    op.drop_table('backaccounts')
    # ### end Alembic commands ###
