"""seed table changes

Revision ID: ae3bcecb7354
Revises: 1bde8f971ed7
Create Date: 2022-12-03 13:06:17.229392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3bcecb7354'
down_revision = '1bde8f971ed7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
